# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 László Pere

"""Long-form per-function help: the multi-paragraph detail text the help tool
returns for the functions section when details=true.

One entry per callable in FUNCTION_ARITIES, keyed by the same name; a drift-guard
test keeps the two registries in lockstep. The text is prose ONLY -- the call
signature and arity are rendered separately by reference._function_details(), so an
entry must not repeat them. Authored to match the per-mode method behavior in
value.py (where the code and the one-line FUNCTION_HELP disagree, the code wins).
"""

FUNCTION_DETAILS: dict[str, str] = {
    "abs": (
        "absolute value |x| — drops the sign and returns the magnitude. For a complex value "
        "it is the modulus sqrt(re^2 + im^2). Every real is in domain; there is no refusal."
        "\n\n"
        "Exact in every real mode: dropping a sign never crosses the grid, so the result is "
        "representable everywhere and the operand's inexact flag carries through unchanged "
        "(an inexact input stays inexact). Float keeps -0.0 handling via the dunder."
    ),
    "acos": (
        "arccosine, returning an angle in radians within [0, pi]. transcendental, so inexact "
        "except the trivial acos(1) = 0. note the exact landmark is x = 1, not x = 0 (acos(0) "
        "= pi/2 is irrational)."
        "\n\n"
        "domain-restricted to |x| <= 1, like asin: an argument outside [-1, 1] is refused in "
        "every mode. computed as pi/2 - asin(x), reusing asin's machinery. in floating-point "
        "it is math.acos, always inexact. in fixed-point the un-rounded asin is subtracted "
        "from pi/2 at a working scale and rounded once; always inexact except acos(1) = 0, "
        "which is exact."
        "\n\n"
        "rational refuses any in-domain argument other than 1: acos of such a rational is "
        "irrational, so it raises. only acos(1) = 0 is allowed, and it is exact; "
        "out-of-domain still refuses."
    ),
    "acosh": (
        "inverse hyperbolic cosine, acosh(x) = ln(x + sqrt(x**2 - 1)) — the inverse of cosh "
        "on its principal branch. DOMAIN x >= 1 (cosh's range); an argument below 1 raises "
        "NotRepresentableError in every mode. transcendental like log, so inexact except "
        "acosh(1) = 0."
        "\n\n"
        "fixed-point: supported via the ln core for x > 1; always inexact except acosh(1) = "
        "0, which is exact (the radicand vanishes and ln(1) = 0). floating-point: math.acosh, "
        "unconditionally inexact. rational: acosh of a rational is irrational, so any "
        "in-domain argument other than 1 refuses with NotRepresentableError; only acosh(1) = "
        "0 is representable."
    ),
    "arg": (
        "argument/phase arg(z) in radians — atan2(Im z, Re z), the angle of z measured from "
        "the positive real axis, in the principal range (-pi, pi]. On a real value this is "
        "atan2(0, x): 0 for x >= 0 and pi for x < 0. In complex mode it takes the angle of "
        "the stored real and imaginary parts."
        "\n\n"
        "Unlike re/im/conj this is genuine trigonometry, so it inherits atan2's per-mode "
        "behavior rather than being an exact selection: fixed-point and floating-point return "
        "an inexact (rounded) angle, while rational refuses the result because the angle (and "
        "pi itself) is generally irrational and not representable as an exact fraction."
    ),
    "asin": (
        "arcsine, returning an angle in radians within [-pi/2, pi/2]. transcendental, so "
        "inexact except the trivial asin(0) = 0."
        "\n\n"
        "domain-restricted to |x| <= 1: an argument outside [-1, 1] has no real arcsine and "
        "is refused in every mode (mirrors sqrt's refusal of a negative operand). in "
        "floating-point it is math.asin, always inexact. in fixed-point it is computed as "
        "atan(x / sqrt(1 - x**2)) through the internal arctan series and fixed-point sqrt "
        "with guard digits, rounded half-to-even back; always inexact except asin(0) = 0."
        "\n\n"
        "rational refuses any in-domain non-zero argument: asin of a non-zero rational is "
        "irrational, so it raises. only asin(0) = 0 is allowed, and it is exact; "
        "out-of-domain still refuses."
    ),
    "asinh": (
        "inverse hyperbolic sine, asinh(x) = ln(x + sqrt(x**2 + 1)) — the inverse of sinh. "
        "odd, defined for all reals (no domain restriction). transcendental like log, so "
        "inexact except asinh(0) = 0."
        "\n\n"
        "fixed-point: supported via the ln core; asinh is odd so the sign is folded and the "
        "magnitude computed on |x|. always inexact except asinh(0) = 0, which is exact. "
        "floating-point: math.asinh, unconditionally inexact. rational: asinh of a rational "
        "reduces to a logarithm and is transcendental, so it refuses any non-zero argument "
        "with NotRepresentableError; only asinh(0) = 0 is representable."
    ),
    "atan": (
        "arctangent, returning an angle in radians within (-pi/2, pi/2). transcendental, so "
        "inexact except the trivial atan(0) = 0."
        "\n\n"
        "unrestricted domain: every real has an arctangent, so unlike asin/acos no argument "
        "is ever refused for range. in floating-point it is math.atan, always inexact. in "
        "fixed-point it is the internal arctan series at the operand's scale plus guard "
        "digits, rounded half-to-even back, with arguments above 1 reduced via atan(x) = pi/2 "
        "- atan(1/x); always inexact except atan(0) = 0."
        "\n\n"
        "rational refuses any non-zero argument: atan of a non-zero rational is irrational, "
        "so it raises. only atan(0) = 0 is allowed, and it is exact."
    ),
    "atan2": (
        "two-argument quadrant-aware arctangent atan2(y, x): the angle in radians of the "
        "point (x, y) measured from the positive x-axis, within (-pi, pi]. unlike plain "
        "atan(y/x) it uses the signs of both arguments to pick the correct quadrant, so it "
        "distinguishes (x, y) from (-x, -y) and is defined when x = 0. the first argument is "
        "y, the second is x (math.atan2 order). transcendental, so inexact except the single "
        "landmark atan2(0, x>=0) = 0, which also fixes atan2(0, 0) = 0."
        "\n\n"
        "domain is all real (y, x) pairs; nothing is refused for range. in floating-point it "
        "is math.atan2, always inexact. in fixed-point the base angle atan(|y/x|) is the "
        "arctan series at the covering scale plus guard digits (the ratio fed in un-rounded), "
        "offset by pi or pi/2 for the quadrant and rounded half-to-even; always inexact "
        "except the zero landmark."
        "\n\n"
        "rational refuses every point except atan2(0, x>=0) = 0: any other angle is an "
        "irrational multiple/sum involving pi or an irrational arctan, so it raises. the one "
        "allowed case is exact."
    ),
    "atanh": (
        "inverse hyperbolic tangent, atanh(x) = ln((1 + x)/(1 - x))/2 — the inverse of tanh. "
        "odd. DOMAIN |x| < 1 (tanh's open range); x = +/-1 is +/-inf and any argument with "
        "|x| >= 1 raises NotRepresentableError in every mode. transcendental like log, so "
        "inexact except atanh(0) = 0."
        "\n\n"
        "fixed-point: supported via the public ln core (not the bare atanh series, which is "
        "ln's own internal piece); atanh is odd so the sign is folded and the magnitude "
        "computed on |x|. always inexact except atanh(0) = 0, which is exact. floating-point: "
        "math.atanh, unconditionally inexact. rational: atanh of a rational is "
        "transcendental, so any other in-domain argument refuses with NotRepresentableError; "
        "only atanh(0) = 0 is representable."
    ),
    "avg": (
        "arithmetic mean: the running total of the operands folded over + (exact like "
        "repeated addition), then divided by the count carried as a same-mode whole number. "
        "avg(a) is a / 1."
        "\n\n"
        "takes either a flat run of operands or a single vector whose elements are averaged "
        "(avg([a, b, ...])); a vector is legal only as the sole operand, and an empty vector "
        "is refused (mean of no values is undefined). the divisor is built in the operands' "
        "own mode (the element mode when reducing a vector)."
        "\n\n"
        "the final divide follows the mode's / rule: rational is exact, fixed-point quantizes "
        "to the covering scale and may round, float rounds. widen min_fixed_point_precision "
        "for more accuracy in fixed-point."
    ),
    "bps": (
        "computes b basis points of x as x*b/10000 — the basis-point twin of pct, existing "
        "solely to make the bps-vs-percent distinction un-confusable at the call site (25 bps "
        "is 0.25%, not 25%). bps(x, 10000) is x and bps(x, 100) equals pct(x, 1)."
        "\n\n"
        "the multiply happens first, then a divide by a whole 10000, so the result follows "
        "the active mode's / rule: fixed-point quantizes to the covering scale and may round, "
        "float rounds, rational stays exact. both arguments must be the same mode."
    ),
    "cbrt": (
        "cube root x**(1/3) — the shape of sqrt, inexact except where the root lands exactly "
        "on the mode's grid. The one difference: a cube root is an ODD root, so NEGATIVE "
        "inputs are in domain — cbrt(-8) == -2, real — not the refusal sqrt raises on "
        "negatives. Refuses complex."
        "\n\n"
        "floating-point: sign-preserving via copysign(abs(x)**(1/3), x), unconditionally "
        "inexact. fixed-point: SUPPORTED — the integer cube root of the mantissa rescaled to "
        "the operand's scale, rounded to nearest (a negative mantissa cube-roots its "
        "magnitude and keeps the sign); exact only when the operand was exact AND it is a "
        "perfect cube at that scale. rational: exact ONLY when numerator and denominator are "
        "BOTH perfect cubes (a negative numerator is fine — odd root); otherwise irrational "
        "and it refuses."
    ),
    "ceil": (
        "round toward positive infinity — the mirror of floor: ceil(2.1) -> 3, ceil(-2.7) -> "
        "-2. Same optional ndigits count (default 0); negative ndigits rounds to "
        "tens/hundreds, e.g. ceil(1234, -2) -> 1300. ndigits must be an integer (a "
        "non-integer refuses). Refuses complex."
        "\n\n"
        "Exact in every mode — ceiling SELECTS a representable value — EXCEPT floating-point "
        "with ndigits > 0, where the n-decimal target is not binary-representable (inexact); "
        "ceiling a float to an integer (ndigits <= 0) stays exact. Fixed-point computes "
        "ceiling as -floor(-x) on the mantissa and rational ceils the shifted fraction — both "
        "always exact."
    ),
    "clamp": (
        "constrain x to the range [lo, hi] = min(hi, max(lo, x)). ternary fixed-arity-3: x is "
        "the first argument, then lo and hi. x below lo gives lo, above hi gives hi, "
        "otherwise x is returned untouched."
        "\n\n"
        "SELECTION, not math, like max/min: it never computes, returning whichever of the "
        "three operands applies VERBATIM, so the result carries that operand's own scale and "
        "exactness, never rounds, and is EXACT in EVERY mode. comparison is value-only and "
        "same-mode-enforced across all three, so a fixed-point bound compares across scales."
        "\n\n"
        "DOMAIN lo <= hi: an inverted range is meaningless and REFUSES."
    ),
    "comb": (
        "binomial coefficient C(n, k) = n!/(k!(n-k)!), the count of k-element subsets of an "
        "n-set. binary fixed-arity-2: self is n, other is k. integer-only: both operands go "
        "through _as_integer (so a fractional fixed-point value, a rational with denominator "
        "!= 1, or a non-whole float refuses, since a non-integer argument is the deferred "
        "gamma generalisation), with same-mode enforced. an out-of-range k chooses an "
        "impossible subset and gives 0: k < 0 or k > n (so a negative n folds to 0 as well). "
        "the count of multiplicative terms min(k, n-k) is capped at 1000."
        "\n\n"
        "exact in every mode where defined: math.comb cancels to an integer via the "
        "multiplicative form, never three factorials. fixed-point/rational return the exact "
        "integer at scale 0; floating-point returns float(C(n, k)), refusing on double "
        "overflow and marked exact only when the double represents the integer precisely."
    ),
    "compound": (
        "computes compound growth of the principal as principal*(1+rate)**periods. rate is "
        "PER PERIOD and periods counts the SAME unit, so an annual rate can never silently "
        "act monthly — quote a monthly rate with a month count. compound(p, r, 0) is p (any "
        "base to the 0th power)."
        "\n\n"
        "it builds the per-period factor 1+rate, raises it with **, then scales the "
        "principal, inheriting each mode's power and multiply rules. a WHOLE periods keeps "
        "the power exact (fixed-point mantissa arithmetic, an integer Fraction power in "
        "rational) and only the final multiply may quantize; a FRACTIONAL periods rides the "
        "fractional-exponent path — exact on a perfect root, otherwise an inexact series, and "
        "rational refuses an irrational power."
    ),
    "conj": (
        "complex conjugate — a-bi, the value with the sign of its imaginary part flipped. A "
        "real value equals its own conjugate, so in every non-complex mode this is the "
        "identity: the operand is returned verbatim with its exactness flag intact. In "
        "complex mode it negates the imaginary part and leaves the real part untouched."
        "\n\n"
        "Negation only flips a sign, so this stays exactly on the grid and preserves each "
        "part's exactness; it never rounds."
    ),
    "correlation": (
        "Pearson correlation r of two equal-length vectors: the standardized covariance "
        "cov(x, y) / (stddev(x)*stddev(y)), always in [-1, 1] (+1 perfectly correlated, -1 "
        "perfectly anti-correlated, 0 uncorrelated). both the population covariance and "
        "stddevs use the same n, so it cancels."
        "\n\n"
        "takes TWO vectors, x then y; both must be vectors, of EQUAL length and NON-EMPTY, "
        "else it refuses. additionally a CONSTANT series has zero stddev, so r divides by "
        "zero and RAISES: correlation is undefined when a series does not vary. "
        "correlation([a], [b]) likewise divides 0 by 0."
        "\n\n"
        "inherits stddev's sqrt: ALWAYS inexact in float and fixed-point (the rounded "
        "cov/stddev compound; widen min_fixed_point_precision), and in RATIONAL mode it "
        "REFUSES when either stddev is irrational, exact there only when both variances are "
        "perfect squares."
    ),
    "cos": (
        "cosine of an angle given in radians, same machinery as sin. transcendental, so "
        "inexact everywhere except the trivial cos(0) = 1."
        "\n\n"
        "domain is all reals; nothing is refused for range. in floating-point it is math.cos, "
        "always inexact. in fixed-point the argument is range-reduced mod 2*pi and the even "
        "Taylor series 1 - x**2/2! + x**4/4! - ... is summed on scaled ints with guard "
        "digits, rounded half-to-even back; always inexact except cos(0) = 1, which is exact."
        "\n\n"
        "rational refuses any non-zero argument: cos of a non-zero rational is irrational, so "
        "it raises. only cos(0) = 1 is allowed, and it is exact."
    ),
    "cosh": (
        "hyperbolic cosine, cosh(x) = (e**x + e**-x)/2 — even, with range [1, inf) and no "
        "domain restriction. transcendental like exp, so inexact except the trivial cosh(0) = "
        "1, its only exact landmark (the minimum)."
        "\n\n"
        "fixed-point: supported by combining one un-rounded e**x and e**-x from the exp core; "
        "always inexact except cosh(0) = 1, which is exact. floating-point: math.cosh, "
        "unconditionally inexact. rational: cosh of a rational is transcendental, so it "
        "refuses any non-zero argument with NotRepresentableError; only cosh(0) = 1 is "
        "representable."
    ),
    "cot": (
        "cotangent of an angle given in radians, equal to cos/sin, the mirror of tan. "
        "transcendental and inexact everywhere it is defined; there is no exact landmark, "
        "since cot(0) is undefined (sin = 0)."
        "\n\n"
        "cot is undefined at multiples of pi where sin = 0, including 0 itself. pi is "
        "irrational so that point is never hit exactly off zero; the answer there is just a "
        "large inexact value. in floating-point it is math.cos / math.sin, always inexact, "
        "and a zero sine (a multiple of pi) propagates ZeroDivisionError. in fixed-point both "
        "series are summed at a working scale and divided (the scale cancels), rounded "
        "half-to-even; if the sine series rounds to 0, or the argument is exactly 0, it "
        "raises ZeroDivisionError."
        "\n\n"
        "rational refuses every argument: a non-zero rational gives an irrational cotangent "
        "so it raises, and the argument 0 is undefined (ZeroDivisionError). there is no "
        "allowed exact case."
    ),
    "covariance": (
        "POPULATION covariance of two equal-length vectors: mean((x - mx)*(y - my)) over the "
        "paired elements, where mx/my are the per-vector means (avg). covariance([a], [b]) is "
        "0 (a lone pair has no spread)."
        "\n\n"
        "takes TWO vectors, x then y; both must be vectors, of EQUAL length (an unpaired "
        "series is meaningless) and NON-EMPTY, else it refuses. the two vectors share the "
        "run's element mode, so the paired arithmetic is same-mode by construction."
        "\n\n"
        "no sqrt, so it COMPUTES through the mode's / rule via the means and the final "
        "divide: EXACT in rational, MAY ROUND in fixed-point/float (a rounded mean compounds; "
        "widen min_fixed_point_precision for accuracy). Pearson correlation divides this by "
        "the stddev product."
    ),
    "degrees": (
        "convert an angle from radians to degrees, x*180/pi. this is unit scaling, not a trig "
        "function, and it is the bridge out of the radians-only trig family. it multiplies by "
        "an irrational (1/pi), so it is inexact except the trivial degrees(0) = 0."
        "\n\n"
        "domain is all reals; every real converts, no domain limit. in floating-point it is "
        "math.degrees, always inexact. in fixed-point it forms the exact ratio with the "
        "internal pi at a working scale carrying the argument's integer digits plus guard, "
        "rounded half-to-even to the operand's scale; always inexact except degrees(0) = 0, "
        "which is exact."
        "\n\n"
        "rational refuses any non-zero argument: pi has no rational value so degrees(x) is "
        "irrational, and it raises. only degrees(0) = 0 is allowed, and it is exact."
    ),
    "diff": (
        "numerical derivative: the rate of change of an expression with respect to a named "
        "variable, evaluated at one point. the arguments are diff(expr, var, at): the 1st is "
        "the UNEVALUATED expression, the 2nd a bare variable NAME (not a value) to "
        "differentiate against, the 3rd the point. expr is re-evaluated at several sample "
        "points near the point with var rebound to each; var shadows any outer binding of the "
        "same name and may not be a name the expression assigns."
        "\n\n"
        "the method is a 4th-order five-point central difference, accumulated in the active "
        "mode. a transcendental expression in rational mode refuses at the sample, the same "
        "stance those functions take everywhere."
        "\n\n"
        "diff is ALWAYS inexact, in every type — a finite-difference quotient only "
        "approximates the true derivative, so the result is flagged inexact even when the "
        "underlying arithmetic stayed exact."
    ),
    "e": (
        "Euler's number e, the base of the natural logarithm. takes no arguments and may be "
        "written bare as `e` (no parens) like a literal; the name is reserved and cannot be "
        "assigned to. the mirror of pi."
        "\n\n"
        "e is irrational, so it has no exact representation in any type. in float it is "
        "math.e, the nearest binary64 double; in fixed-point it is e truncated to the run's "
        "nullary precision. both are flagged inexact. rational REFUSES — e has no exact "
        "numerator/denominator."
    ),
    "exp": (
        "the exponential e**x — the inverse of log/ln. defined for all reals (no domain "
        "restriction). transcendental, so inexact except the trivial exp(0) = 1."
        "\n\n"
        "fixed-point: supported via an all-plus Taylor series after range-reducing by ln(2) "
        "(write x = k*ln2 + s so exp(x) = 2**k * exp(s)); always inexact except exp(0) = 1, "
        "which is exact. floating-point: math.exp, unconditionally inexact. rational: exp of "
        "a rational is transcendental, so it refuses any non-zero argument with "
        "NotRepresentableError; only exp(0) = 1 is representable."
    ),
    "factor": (
        "prime factorisation of a positive integer, unary, and the first function whose "
        "result is a vector. the prime factors come back in ascending order with "
        "multiplicity, so their product reconstructs the operand: factor(12) = [2, 2, 3], "
        "factor(7) = [7], factor(1) = [] (the empty product). the factors are packed into a "
        "one-dimensional vector carrying the run's element mode."
        "\n\n"
        "integer-only, the gcd/lcm stance: the operand goes through _as_integer (so a "
        "fractional fixed-point value, a rational with denominator != 1, a non-whole float, "
        "or any complex value refuses) and it must be positive, so 0 and negatives refuse; 1 "
        "is the empty product, not an error. the operand is capped at 10**12 so a huge value "
        "cannot lock the process up in trial division."
        "\n\n"
        "exact in fixed-point/rational: a 2,3-wheel trial division on Python ints never "
        "leaves the grid and each factor is a whole number at scale 0. in floating-point each "
        "element carries the usual binary64 inexact flag (a float value is unconditionally "
        "inexact even though the small factors are exactly representable), so the vector "
        "reports inexact; an empty result (factor(1)) is vacuously exact in every mode."
    ),
    "factorial": (
        "n! for a non-negative integer n, unary. domain is non-negative integers only: the "
        "operand goes through _as_integer (so a fractional fixed-point value, a rational with "
        "denominator != 1, or a non-whole float refuses) and a negative operand also refuses, "
        "since the negative and non-integer cases are the continuous gamma extension. n is "
        "capped at 1000 so a huge operand cannot lock the process up building an astronomical "
        "integer."
        "\n\n"
        "exact in every mode where defined, being a product of integers. fixed-point/rational "
        "return the exact integer math.factorial(n) at scale 0. floating-point returns "
        "float(n!), refusing once that overflows a double (~n > 170, well under the cap), and "
        "is marked exact only when the double represents n! precisely (every n <= 18, plus "
        "some larger n via the trailing factors of two)."
    ),
    "floor": (
        "round toward negative infinity — floor(2.7) -> 2, floor(-2.1) -> -3. Takes an "
        "optional second arg ndigits (default 0) fixing how many decimal places to floor at; "
        "negative ndigits rounds to tens/hundreds, e.g. floor(1234, -2) -> 1200. ndigits must "
        "be an integer in the current mode (a non-integer refuses); its exactness flag is "
        "irrelevant. Refuses complex (no ordering)."
        "\n\n"
        "Exact in every mode — flooring SELECTS a representable value, it does not compute — "
        "EXCEPT floating-point with ndigits > 0, where the n-decimal target (e.g. 2.70) is "
        "not binary-representable and the result is inexact; flooring a float to an integer "
        "(ndigits <= 0) lands on a whole multiple a double holds exactly, so it stays exact. "
        "Fixed-point uses // on the scaled mantissa (Python // already floors) and rational "
        "floors the shifted fraction — both always exact."
    ),
    "fv": (
        "computes the future value of an nper-period stream of level payments pmt at the "
        "per-period rate r — the ordinary-annuity accumulation — as fv = "
        "pmt*((1+r)**nper-1)/r. with a zero rate the payments just add up, pmt*nper. argument "
        "order is rate, nper, pmt."
        "\n\n"
        "same trio convention as pmt: ordinary annuity (payment at period end), no sign flip, "
        "rate per period over nper like-unit periods. the annuity form complements compound, "
        "which grows a lump sum rather than a payment stream. it composes +, **, -, * and /, "
        "so a whole nper keeps the power exact and the final / r follows the mode's rule: "
        "fixed-point quantizes and may round, float rounds, rational stays exact."
    ),
    "gcd": (
        "greatest common divisor of one or more operands, variadic: the first operand is "
        "self, so gcd(a) is |a| (the one-operand fold), and a single vector operand is "
        "reduced over its elements. integer-only: every operand goes through _as_integer, so "
        "a fixed-point value with a fractional part, a rational with denominator != 1, or a "
        "non-whole float refuses. sign is dropped (the gcd is taken of the magnitudes) and "
        "gcd(0, 0) is 0."
        "\n\n"
        "exact in every mode: pure integer arithmetic on the operand magnitudes never leaves "
        "the grid, so there is no rounding and no inexact flag. same-mode is enforced like "
        "every variadic, and the result is a whole number at scale 0 in fixed-point."
    ),
    "hypot": (
        "euclidean norm sqrt(x1^2 + x2^2 + ... + xn^2) — VARIADIC: self is the first "
        "coordinate, so hypot(x) is just |x| and hypot(a, b) is the leg-to-hypotenuse "
        "sqrt(a^2 + b^2). Every real is in domain — squaring erases the sign — so unlike sqrt "
        "there is no negative refusal. Refuses complex."
        "\n\n"
        "Inherits sqrt's stance: the norm is irrational in general, so inexact in "
        "float/fixed-point and exact in rational only when the sum of squares is a perfect "
        "square. Crucially the sum of squares is accumulated EXACTLY (not by folding over "
        "mul/add, which would round each square first) and rounded ONCE at the final root — a "
        "single half-ULP rounding."
        "\n\n"
        "floating-point: math.hypot, which avoids the intermediate overflow naive squaring "
        "suffers; unconditionally inexact. fixed-point: SUPPORTED (crypto) — squared "
        "mantissas summed as exact bignums, then the rounded integer sqrt at the covering "
        "scale (max of the operands' decimals); exact only when EVERY operand was exact AND "
        "the sum is a perfect square. rational: exact sum of squares then sqrt's "
        "exact-or-refuse — exact only when both parts of the sum are perfect squares, "
        "otherwise it refuses."
    ),
    "im": (
        "imaginary part Im(z) — the b (the real coefficient of i) in a+bi, not b*i. Zero in "
        "every real mode, since a real has no imaginary part: returns an exact 0 in the "
        "current mode. In complex mode it selects the stored imaginary coefficient and "
        "returns it as a complex value with zero imaginary part."
        "\n\n"
        "Like re, this is a selection rather than a computation: it carries the exactness of "
        "the part it extracts and never rounds."
    ),
    "integral": (
        "definite integral: the signed area under an expression over the interval [a, b]. the "
        "arguments are integral(expr, var, a, b): the 1st is the UNEVALUATED integrand, the "
        "2nd a bare variable NAME (not a value) — the integration variable, the 3rd and 4th "
        "the bounds. expr is re-evaluated at many sample points with var rebound to each; var "
        "shadows any outer binding of the same name and may not be a name the integrand "
        "assigns. a zero-width interval (a == b) gives 0."
        "\n\n"
        "the method is adaptive-Simpson quadrature, accumulated in the active mode with no "
        "float shadow. a transcendental integrand in rational mode refuses at the sample, the "
        "same consistent stance those functions take everywhere."
        "\n\n"
        "integral is ALWAYS inexact, in every type — Simpson's rule only approximates the "
        "true integral, so the result is flagged inexact even when the accumulating "
        "arithmetic stayed exact (e.g. a cubic in rational mode)."
    ),
    "lcm": (
        "least common multiple of one or more operands, the multiplicative twin of gcd: same "
        "variadic shape (lcm(a) is |a|, a single vector operand is reduced over its "
        "elements), same integer-only domain. every operand goes through _as_integer, so a "
        "fractional fixed-point value, a rational with denominator != 1, or a non-whole float "
        "refuses; sign is dropped, and any zero operand makes the whole result 0 (0 shares "
        "every multiple)."
        "\n\n"
        "exact in every mode: the fold lcm(a, b) = |a*b|/gcd(a, b) stays in the integers, so "
        "no rounding and no inexact flag. same-mode is enforced and the result is a whole "
        "number at scale 0 in fixed-point."
    ),
    "lerp": (
        "linear interpolation a + (b - a)*t. ternary fixed-arity-3: a (the t=0 endpoint) is "
        "the first argument, then b (the t=1 endpoint) and t (the fraction). t=0 gives a, t=1 "
        "gives b; t is unrestricted, so t in [0, 1] interpolates and t outside extrapolates "
        "past the endpoints."
        "\n\n"
        "plain ARITHMETIC, not selection: composed straight from sub/mul/add, so it inherits "
        "their per-mode stance exactly (the avg/division family) — EXACT in rational, and MAY "
        "ROUND in fixed-point/float where the *t multiply leaves the grid. same-mode is "
        "enforced by the underlying ops."
    ),
    "ln": (
        "natural logarithm base e — the strictly unary spelling of log(x). identical behavior "
        "to unary log: domain x > 0 (refuses x <= 0 in every mode), transcendental so inexact "
        "except ln(1) = 0."
        "\n\n"
        "kept strictly unary on purpose: log overloads to log(x, base), but ln means "
        "natural-log-only, so it never takes a base. fixed-point: supported via the ln core "
        "(base-10 reduction plus an atanh series), inexact except ln(1) = 0. floating-point: "
        "math.log, unconditionally inexact. rational: transcendental except ln(1) = 0, which "
        "alone is representable; any other argument refuses."
    ),
    "log": (
        "natural logarithm base e when unary; the GENERAL logarithm log(x, base) = "
        "log(x)/log(base) when a second operand supplies the base. transcendental, so inexact "
        "except the trivial log(1) = 0. DOMAIN x > 0: a non-positive operand (x = 0 is -inf, "
        "x < 0 undefined) refuses with NotRepresentableError in every mode, mirroring sqrt's "
        "negative refusal. the two-arg form additionally refuses base <= 0 or base = 1."
        "\n\n"
        "the two-arg log(x, base) is EXACT only when x is an integer power of base — log(8, "
        "2) = 3, log(1, base) = 0, log(base, base) = 1 — which lands the whole exponent with "
        "no rounding; every other case is transcendental."
        "\n\n"
        "fixed-point: supported via a base-10 reduction plus an atanh series (the ln core), "
        "ln(x) = n*ln(10) + 2*atanh((r-1)/(r+1)); always inexact except log(1) = 0. "
        "floating-point: math.log, unconditionally inexact even on a landmark. rational: log "
        "of a rational is transcendental except log(1) = 0 (and, for the two-arg form, an "
        "integer-power landmark, which returns the exponent exactly); otherwise "
        "NotRepresentableError, the exact-or-refuse stance of sqrt."
    ),
    "log10": (
        "base-10 logarithm, log10(x) = log(x)/ln(10) — transcendental like log but with "
        "richer exact landmarks, since the base-10 reduction splits x = r*10**n and a power "
        "of ten (r = 1) logs to the whole number n exactly. DOMAIN x > 0; a non-positive "
        "operand refuses with NotRepresentableError in every mode, like log."
        "\n\n"
        "fixed-point: supported. a power of ten at the operand's scale (mantissa == 10**j) is "
        "the exponent j - decimals exactly — log10(100) = 2, log10(0.001) = -3; otherwise the "
        "ln core divided by the ln(10) constant, quantized to the operand's scale, inexact. "
        "floating-point: math.log10, unconditionally inexact. rational: log10 of a rational "
        "is irrational unless x is an integer power of ten (x = 10**k, k possibly negative "
        "like 1/10), where it returns k exactly; every other argument refuses — the log "
        "analogue of sqrt's perfect-square set."
    ),
    "log2": (
        "base-2 logarithm, log2(x) = log(x)/ln(2) — transcendental like log, included because "
        "this engine is bit-oriented (entropy / bit-width work). DOMAIN x > 0; a non-positive "
        "operand refuses with NotRepresentableError in every mode, like log."
        "\n\n"
        "unlike log10 the argument reduction is base 10, not base 2, so a power of two does "
        "NOT fall out exactly — the ONLY exact landmark is the trivial log2(1) = 0. "
        "fixed-point: supported via the ln core divided by the ln(2) constant, quantized to "
        "the operand's scale; inexact except log2(1) = 0. floating-point: math.log2, "
        "unconditionally inexact. rational: log2 of a rational is irrational except log2(1) = "
        "0, which alone is representable; any other argument refuses, the exact-or-refuse "
        "stance of log."
    ),
    "map": (
        "element-wise transform of a vector: apply a body expression to every element and "
        "collect a same-length vector. the arguments are map(vector, name, body): the 1st is "
        "the source vector (an ordinary expression, evaluated up front — it MUST be a vector, "
        "a scalar refuses since map is vector-in/vector-out), the 2nd a bare NAME (not a "
        "value) — the element dummy, the 3rd the UNEVALUATED body re-evaluated once per "
        "element with name rebound to it. name shadows any outer binding of the same name and "
        "may not be a name the body assigns. map([1,2,3], x, x**2) = [1, 4, 9]; an empty "
        "vector maps to an empty vector."
        "\n\n"
        "it is the missing element-wise primitive — the vector type otherwise refuses every "
        "operator and function, so map is how you transform a series. the FIRST function that "
        "both CONSUMES and PRODUCES a vector, reusing factor's producer plumbing. a "
        "transcendental body in rational mode refuses at the element, the same stance the "
        "other special forms take."
        "\n\n"
        "map itself only DISPATCHES — it adds no arithmetic and stamps no verdict of its own. "
        "exactness is the BODY's, per element: the result is exact iff every mapped element "
        "is (an empty source is vacuously exact); a fixed-point body that rounds, or a float "
        "body, makes the elements — and so the vector — inexact."
    ),
    "max": (
        "largest operand, returned VERBATIM: pure selection, never math. it compares "
        "value-only and returns whichever operand is greatest unchanged, so the result "
        "carries that operand's own scale and exactness and is EXACT in every mode (exact iff "
        "the chosen operand was). a tie keeps the earlier operand (strict >)."
        "\n\n"
        "takes either a flat run of operands or a single vector reduced over its elements "
        "(max([a, b, ...]) is the largest element); a vector is legal only as the sole "
        "operand, and an empty vector is refused. max(a) is a."
        "\n\n"
        "comparison is same-mode-enforced and value-only, so a fixed-point pair compares "
        "across scales (1.5 == 1.50). complex has no total order, so it refuses rather than "
        "invent a magnitude order. mirror of min."
    ),
    "median": (
        "middle operand by value. sorts the operands value-only (no arithmetic, so the "
        "ordering never rounds). an ODD count has a single middle, returned VERBATIM like "
        "max/min, so it carries that operand's own scale and exactness and is exact. an EVEN "
        "count averages the two straddling middles, (lo + hi) / 2, which COMPUTES."
        "\n\n"
        "takes either a flat run of operands or a single vector whose elements are used "
        "(median([a, b, ...])); a vector is legal only as the sole operand, and an empty "
        "vector is refused. median(a) is a (odd count 1)."
        "\n\n"
        "the even-count average follows the mode's / rule exactly as avg: rational is exact, "
        "fixed-point may round, float rounds. median equals quantile(0.5, ...) and "
        "percentile(50, ...)."
    ),
    "min": (
        "smallest operand, returned VERBATIM: the mirror of max. pure selection, never math, "
        "so the result carries the chosen operand's own scale and exactness and is EXACT in "
        "every mode. a tie keeps the earlier operand (strict <)."
        "\n\n"
        "takes either a flat run of operands or a single vector reduced over its elements "
        "(min([a, b, ...]) is the smallest element); a vector is legal only as the sole "
        "operand, and an empty vector is refused. min(a) is a."
        "\n\n"
        "comparison is same-mode-enforced and value-only, so a fixed-point pair compares "
        "across scales; complex has no total order and refuses."
    ),
    "pct": (
        "computes p percent of x as x*p/100 — the everyday percentage op, named so the caller "
        "never hand-rolls the /100 (the off-by-100 / 25-bps-read-as-25% class). pct(x, 0) is "
        "0, pct(x, 100) is x; for basis points use bps instead."
        "\n\n"
        "the multiply happens first, then a divide by a whole 100, so the result follows the "
        "active mode's / rule: fixed-point quantizes to the covering scale and may round, "
        "float rounds, rational stays exact. both arguments must be the same mode."
    ),
    "pct_change": (
        "computes the signed relative change from old to new as (new-old)/old, a fraction — "
        "multiply by 100, or feed to pct, for a percentage. pct_change(x, x) is 0; a positive "
        "jump gives a positive result, a drop a negative one."
        "\n\n"
        "old is the first argument and the denominator, so pct_change(0, x) divides by zero "
        "and raises like any / by zero. it composes a subtract then a divide, so it follows "
        "the mode's / rule: fixed-point quantizes and may round, float rounds, rational stays "
        "exact."
    ),
    "percentile": (
        "value at percentile rank p in [0, 100] of the data: quantile scaled by 100, so "
        "percentile(p, ...) is quantile(p / 100, ...). p is the first argument, the data "
        "follows (arity (2, None)), or a single vector percentile(p, [a, b, ...]). "
        "percentile(50, ...) equals median."
        "\n\n"
        "shares quantile's LINEAR type-7 core: sorts by value, reads rank (n - 1)*p / 100 "
        "computed exactly as a Fraction, selects the datum VERBATIM when the rank is integral "
        "(exact), else interpolates linearly between the two straddling data."
        "\n\n"
        "the interpolation follows the mode's stance: rational exact, fixed-point may round, "
        "float inexact. DOMAIN: p in [0, 100] (outside refuses) and the point must be a "
        "scalar. percentile(p, a) is a."
    ),
    "perm": (
        "falling factorial P(n, k) = n!/(n-k)!, the count of ordered k-permutations of an "
        "n-set, comb's order-aware twin. binary fixed-arity-2: self is n, other is k. "
        "integer-only: both operands go through _as_integer (so a fractional fixed-point "
        "value, a rational with denominator != 1, or a non-whole float refuses, since a "
        "non-integer argument is the deferred gamma generalisation), with same-mode enforced. "
        "an out-of-range k arranges an impossible selection and gives 0: k < 0 or k > n (so a "
        "negative n folds to 0 as well). the count of multiplicative terms k is capped at "
        "1000."
        "\n\n"
        "exact in every mode where defined: math.perm is the product of k consecutive "
        "integers, so no rounding. fixed-point/rational return the exact integer at scale 0; "
        "floating-point returns float(P(n, k)), refusing on double overflow and marked exact "
        "only when the double represents the integer precisely."
    ),
    "pi": (
        "the circle constant pi, the ratio of a circle's circumference to its diameter. takes "
        "no arguments and may be written bare as `pi` (no parens) so `2*pi` reads it like a "
        "literal; the name is reserved and cannot be assigned to."
        "\n\n"
        "pi is irrational, so it has no exact representation in any type. in float it is "
        "math.pi, the nearest binary64 double; in fixed-point it is pi truncated to the run's "
        "nullary precision (the derived decimal scale). both are flagged inexact. rational "
        "REFUSES — pi has no exact numerator/denominator."
    ),
    "pmt": (
        "computes the level payment amortising a present value pv to zero over nper periods "
        "at the per-period rate r — the loan/amortisation case — as pmt = "
        "pv*r/(1-(1+r)**-nper). with a zero rate there is no interest, so it falls back to "
        "the principal split evenly, pv/nper. argument order is rate, nper, pv."
        "\n\n"
        "the trio (pmt/fv/pv) uses the ordinary-annuity convention: payment at each period "
        "END, a residual of 0, and NO sign flip, so a positive loan gives a positive payment "
        "(unlike a spreadsheet). rate is PER PERIOD and nper counts the SAME unit. it "
        "composes +, **, -, * and /, so the negative-integer power inverts exactly in "
        "fixed-point and rational while the divides follow the mode's / rule: fixed-point "
        "quantizes and may round, float rounds, rational stays exact. nper of 0 divides by "
        "zero, the amortisation being undefined."
    ),
    "pow": (
        "x to the power y — the call form of the ** operator, fixed arity 2, identical "
        "behavior. The whole exact-or-refuse stance depends on the mode and the exponent."
        "\n\n"
        "floating-point: x ** y; a negative base to a fractional exponent goes complex, which "
        "a double cannot hold, so it refuses. Inexact when the operands are. rational: an "
        "INTEGER exponent only — exact (a negative exponent just inverts the Fraction); a "
        "non-integer exponent is irrational and refuses. fixed-point: an INTEGER exponent is "
        "EXACT (negative inverts; a zero base to a negative power is a ZeroDivisionError). A "
        "FRACTIONAL exponent p/q is the q-th root of x**p: if it lands exactly on the grid "
        "(both parts of x**p are perfect q-th powers) the result is that exact rational — "
        "this reaches odd roots of negative bases, e.g. (-32)**0.2 == -2, while an even root "
        "of a negative base refuses as complex. Otherwise the root is irrational and computed "
        "inexactly via exp(y*ln x) for a positive base; a negative base with an irrational "
        "root refuses."
    ),
    "product": (
        "range product Π: fold a body expression over an integer index running from a lower "
        "to an upper bound, both INCLUSIVE. the arguments are product(index, lo, hi, body): "
        "the 1st is a bare index NAME (not a value), the 2nd and 3rd the bounds, and the 4th "
        "the UNEVALUATED body re-evaluated once per integer step with the index rebound to "
        "each value. the index shadows any outer binding of the same name and may not be a "
        "name the body itself assigns."
        "\n\n"
        "the bounds must be integers — a fractional or non-whole bound refuses — and the fold "
        "steps by one integer at a time, so the term count is capped at 100000 (a wider range "
        "refuses rather than grinds). an empty range (lo > hi) yields 1."
        "\n\n"
        "product is repeated *, so the fold adds no truncation of its own but follows the "
        "multiply's per-mode story: exact in rational, may round to the covering scale in "
        "fixed-point, rounds in float. any inexactness is the body's or the multiply's, never "
        "the form's."
    ),
    "pv": (
        "computes the present value of an nper-period stream of level payments pmt at the "
        "per-period rate r — the ordinary-annuity discount, the inverse of pmt — as pv = "
        "pmt*(1-(1+r)**-nper)/r. with a zero rate the undiscounted payments just add up, "
        "pmt*nper. argument order is rate, nper, pmt."
        "\n\n"
        "same trio convention (ordinary annuity, no sign flip, rate per period over like-unit "
        "nper periods), the annuity complement to compound. it composes +, **, -, * and /, so "
        "the negative-integer power inverts exactly in fixed-point and rational while the / r "
        "follows the mode's rule: fixed-point quantizes and may round, float rounds, rational "
        "stays exact."
    ),
    "quantile": (
        "value at quantile fraction q in [0, 1] of the data, using the LINEAR / type-7 "
        "convention (NumPy's and R's default). q is the first argument, the data follows "
        "(arity (2, None): a point plus >= 1 datum), or a single vector quantile(q, [a, b, "
        "...]). it is the order-statistic generalisation of median, which is exactly "
        "quantile(0.5, ...)."
        "\n\n"
        "sorts the data by value and reads the value at fractional rank h = (n - 1)*q. when h "
        "lands on an integer rank the datum is returned VERBATIM (exact, carrying that "
        "datum's own scale/exactness); otherwise it interpolates linearly between the two "
        "straddling data, x[k] + gamma*(x[k+1] - x[k]), which COMPUTES. the rank itself is "
        "computed exactly as a Fraction position regardless of mode."
        "\n\n"
        "the interpolation follows the mode's stance exactly as median's even case: rational "
        "exact, fixed-point may round (widen min_fixed_point_precision), float inexact. "
        "DOMAIN: q in [0, 1] (outside refuses) and the point must be a scalar. quantile(q, a) "
        "is a (a lone datum is every quantile)."
    ),
    "radians": (
        "convert an angle from degrees to radians, x*pi/180, the inverse of degrees and the "
        "bridge into the radians-only trig family. this is unit scaling, not a trig function. "
        "it multiplies by an irrational (pi), so it is inexact except the trivial radians(0) "
        "= 0."
        "\n\n"
        "domain is all reals; every real converts, no domain limit. in floating-point it is "
        "math.radians, always inexact. in fixed-point it forms the exact ratio with the "
        "internal pi at a working scale carrying the argument's integer digits plus guard, "
        "rounded half-to-even to the operand's scale; always inexact except radians(0) = 0, "
        "which is exact."
        "\n\n"
        "rational refuses any non-zero argument: pi has no rational value so radians(x) is "
        "irrational, and it raises. only radians(0) = 0 is allowed, and it is exact."
    ),
    "re": (
        "real part Re(z) — the a in a+bi. On a real value (any non-complex mode) it is the "
        "identity: the value IS its own real part, so it is returned verbatim with its "
        "exactness flag intact. In complex mode it selects the stored real part and returns "
        "it as a complex value with zero imaginary part."
        "\n\n"
        "A pure selection of an already-stored part, never arithmetic: it neither rounds nor "
        "leaves the grid, so the result is exactly as exact (or inexact) as the part it picks "
        "out."
    ),
    "round": (
        "round to NEAREST, ties to EVEN (banker's rounding) — round(2.5) -> 2, round(3.5) -> "
        "4, round(-2.5) -> -2, round(2.345, 2) -> 2.34. Same optional ndigits count (default "
        "0) as floor/ceil; negative ndigits rounds to tens/hundreds and ndigits must be an "
        "integer (a non-integer refuses). Half-to-even matches Python's builtin round, the "
        "IEEE-754 default, and the engine's own fixed-point quantiser — the whole engine "
        "rounds one way. Refuses complex."
        "\n\n"
        "Exact in every mode — rounding SELECTS a representable value — EXCEPT floating-point "
        "with ndigits > 0, where the n-decimal target is not binary-representable (inexact); "
        "rounding a float to an integer (ndigits <= 0) stays exact. Fixed-point uses the "
        "engine's half-even quantiser on the scaled mantissa and rational uses Fraction's "
        "half-even __round__ — both always exact."
    ),
    "residual_sum_squares": (
        "the least-squares cost of a MODEL against paired data: the sum of squared residuals "
        "Σ(ys_i - model(xs_i))**2 (RSS/SSE, spelled out — not a cryptic acronym). the "
        "arguments are residual_sum_squares(expr, var, xs, ys): the 1st is the UNEVALUATED "
        "model expression, the 2nd a bare variable NAME (not a value) — the model's free "
        "variable, the 3rd and 4th two EQUAL-LENGTH, NON-EMPTY vectors of the observed x and "
        "y. the two series walk in LOCKSTEP: for each pair expr is re-evaluated with var bound "
        "to xs_i, subtracted from ys_i, squared, and summed. var shadows any outer binding of "
        "the same name and may not be a name the model assigns. this is the direct answer to "
        "'squared distance of a set of (x, y) points from an expression' — the caller-supplied-"
        "model analogue of curve_fit's residual error (which only ranks its built-in forms)."
        "\n\n"
        "RETURNS a scalar. like sum/product it is a finite fold that stamps no verdict of its "
        "own — the per-mode stance is the arithmetic's (subtract + square + add): EXACT in "
        "rational, and MAY ROUND in fixed-point/float where the square leaves the grid (the "
        "sum/avg family, NOT sqrt's — there is no root). widen min_fixed_point_precision for "
        "accuracy. a transcendental model in rational mode refuses at the point, the same "
        "stance the other special forms take."
        "\n\n"
        "DOMAIN: xs and ys must be two equal-length, non-empty vectors — unequal lengths "
        "(unpaired data) and empty data both REFUSE, mirroring covariance. the plural name "
        "residuals(expr, var, xs, ys), returning the signed per-point gap VECTOR, is reserved "
        "for a future sibling."
    ),
    "sign": (
        "signum — returns -1, 0, or +1 by the operand's sign, spelled in the current mode's "
        "own integers. sign(0) is 0, and float -0.0 classifies as 0. It is a comparison to "
        "zero, not arithmetic, so it works on ANY value (integer or not) and never leaves the "
        "grid. Refuses complex (no ordering)."
        "\n\n"
        "The classification is exact in fixed-point and rational REGARDLESS of the operand's "
        "flag — unlike abs, sign reports the sign of the stored value, which is certain, so "
        "an inexact operand still yields an exact sign. Floating-point is the lone exception: "
        "like every binary64 result it carries the unconditional inexact flag even though "
        "-1.0/0.0/+1.0 are representable."
    ),
    "sin": (
        "sine of an angle given in radians. transcendental, so the value is inexact "
        "everywhere except the trivial sin(0) = 0."
        "\n\n"
        "domain is all reals; no argument is refused for being out of range. in "
        "floating-point it is math.sin, always inexact. in fixed-point the argument is "
        "range-reduced mod 2*pi and the Taylor series x - x**3/3! + x**5/5! - ... is summed "
        "on scaled ints with guard digits, rounded half-to-even back to the operand's scale; "
        "always inexact except sin(0) = 0, which is exact."
        "\n\n"
        "rational refuses any non-zero argument: sin of a non-zero rational is irrational "
        "with no scale to round to, so it raises (the same exact-or-refuse stance as sqrt). "
        "only sin(0) = 0 is allowed, and it is exact."
    ),
    "sinh": (
        "hyperbolic sine, sinh(x) = (e**x - e**-x)/2 — odd, with no domain restriction (all "
        "reals). transcendental like exp, so inexact except the trivial sinh(0) = 0."
        "\n\n"
        "fixed-point: supported by combining one un-rounded e**x and e**-x from the exp core, "
        "then halving; always inexact except sinh(0) = 0, which is exact. floating-point: "
        "math.sinh, unconditionally inexact. rational: sinh of a rational is transcendental, "
        "so it refuses any non-zero argument with NotRepresentableError; only sinh(0) = 0 is "
        "representable."
    ),
    "sqrt": (
        "square root — irrational in general, so inexact except where the root lands exactly "
        "on the mode's own grid. A negative operand has no real root and raises an error in "
        "every mode (no complex fallback here)."
        "\n\n"
        "floating-point: math.sqrt, unconditionally inexact (binary64 rounds). fixed-point: "
        "SUPPORTED (crypto) — the exact integer sqrt of the mantissa rescaled to the "
        "operand's scale, rounded to nearest at that scale (a tie is impossible); exact only "
        "when the operand was exact AND it is a perfect square at that scale. rational: exact "
        "ONLY for a perfect square — both numerator and denominator are perfect squares; "
        "otherwise the root is irrational with no scale to round to and it refuses."
    ),
    "stddev": (
        "POPULATION standard deviation: the square root of the population variance (sum of "
        "squared deviations / n). takes either a flat run of operands or a single vector "
        "(stddev([a, b, ...])); a vector is legal only as the sole operand, and an empty "
        "vector is refused. stddev(a) is sqrt(0) = 0."
        "\n\n"
        "inherits sqrt's per-mode story: unconditionally inexact in float and fixed-point. in "
        "RATIONAL mode it refuses (NotRepresentableError) when the root is irrational rather "
        "than fabricate digits, exact there only when the variance is a perfect-square "
        "fraction."
    ),
    "sum": (
        "range summation Σ: fold a body expression over an integer index running from a lower "
        "to an upper bound, both INCLUSIVE. the arguments are sum(index, lo, hi, body): the "
        "1st is a bare index NAME (not a value), the 2nd and 3rd the bounds, and the 4th the "
        "UNEVALUATED body re-evaluated once per integer step with the index rebound to each "
        "value. the index shadows any outer binding of the same name and may not be a name "
        "the body itself assigns."
        "\n\n"
        "the bounds must be integers — a fractional or non-whole bound refuses — and the fold "
        "steps by one integer at a time, so the term count is capped at 100000 (a wider range "
        "refuses rather than grinds). an empty range (lo > hi) yields 0."
        "\n\n"
        "sum is repeated +, so the fold is EXACT in every type: it adds the body's own Values "
        "with no truncation of its own and inherits the body's per-mode story. any "
        "inexactness in the result is the body's, never the form's."
    ),
    "sumsq": (
        "sum of squares x1^2 + x2^2 + ... + xn^2 — VARIADIC, or over a single vector "
        "(sumsq([a, b, ...])); a vector is legal only as the sole operand, and an empty vector "
        "is refused. every real is in domain (squaring erases the sign), so there is no "
        "refusal; sumsq(a) is just a^2. it is the inner sum hypot roots (exposed on its own) "
        "and the reduce half of residual_sum_squares."
        "\n\n"
        "unlike hypot — which accumulates the squares EXACTLY at the doubled scale for a "
        "single final rounding under the root — sumsq takes the avg/variance stance: it folds "
        "the type's own mul then add, so each square quantizes on the type's grid BEFORE "
        "summing. addition never leaves the grid, so the total is EXACT in rational and MAY "
        "ROUND in fixed-point/float, but only where a square already did (fixed-point mul "
        "quantizes to the covering scale, binary64 rounds every product)."
    ),
    "tan": (
        "tangent of an angle given in radians, equal to sin/cos. transcendental, so inexact "
        "everywhere except the trivial tan(0) = 0."
        "\n\n"
        "tan is undefined at odd multiples of pi/2 where cos = 0. pi is irrational so that "
        "point is never hit exactly; the answer there is just a large inexact value. in "
        "floating-point it is math.tan, always inexact. in fixed-point both the sine and "
        "cosine series are summed at a working scale and divided (the scale cancels), rounded "
        "half-to-even to the operand's scale; if the cosine series rounds to 0 at the working "
        "scale the result is undefined and it raises ZeroDivisionError. always inexact except "
        "tan(0) = 0."
        "\n\n"
        "rational refuses any non-zero argument: tan of a non-zero rational is irrational, so "
        "it raises. only tan(0) = 0 is allowed, and it is exact."
    ),
    "tanh": (
        "hyperbolic tangent, tanh(x) = sinh(x)/cosh(x) = (e**x - e**-x)/(e**x + e**-x), with "
        "range (-1, 1). cosh is never zero, so there is NO domain restriction. transcendental "
        "like exp, so inexact except the trivial tanh(0) = 0."
        "\n\n"
        "fixed-point: supported via the exp core (the denominator cosh never vanishes); "
        "always inexact except tanh(0) = 0, which is exact. floating-point: math.tanh, "
        "unconditionally inexact. rational: tanh of a rational is transcendental, so it "
        "refuses any non-zero argument with NotRepresentableError; only tanh(0) = 0 is "
        "representable."
    ),
    "time": (
        "the current Unix epoch in seconds — the wall-clock instant the run was sampled, read "
        "once as integer nanoseconds since 1970-01-01 UTC. takes no arguments. unlike pi/e it "
        "must be written as an explicit call `time()`; it reads the clock, so it is never a "
        "bare constant."
        "\n\n"
        "a clock tick is exactly rational, so time REFUSES in no mode and is inexact only "
        "where the type itself rounds. fixed-point renders at the run's derived scale: scale "
        "0 (the default) gives whole seconds, scales 1..9 give seconds plus fractional "
        "nanoseconds truncated to that many digits, scale >=9 the full nanosecond reading — "
        "exact, the rendered decimal IS the sampled value. rational is the full reading as a "
        "fraction, exact. float is the only mode that rounds the reading into a double, so it "
        "alone is inexact."
    ),
    "trunc": (
        "round toward ZERO — drop the fraction: floor for x >= 0, ceil for x < 0. trunc(2.7) "
        "-> 2, trunc(-2.7) -> -2 (vs floor(-2.7) -> -3); trunc(1290, -2) -> 1200. Same "
        "optional ndigits count (default 0) as the rest of the family; negative ndigits "
        "rounds to tens/hundreds and ndigits must be an integer (a non-integer refuses). "
        "Refuses complex."
        "\n\n"
        "Exact in every mode — truncation SELECTS a representable value — EXCEPT "
        "floating-point with ndigits > 0, where the n-decimal target is not "
        "binary-representable (inexact); truncating a float to an integer (ndigits <= 0) "
        "stays exact. Fixed-point floors the magnitude then restores the sign and rational "
        "truncs the shifted fraction — both always exact."
    ),
    "variance": (
        "POPULATION variance: divides by n (not the sample n-1). composes mean = avg, squares "
        "each deviation op - mean with mul, totals them with repeated +, and divides by the "
        "count. variance(a) is 0 (a lone point has no spread)."
        "\n\n"
        "takes either a flat run of operands or a single vector whose elements are used "
        "(variance([a, b, ...])); a vector is legal only as the sole operand, and an empty "
        "vector is refused."
        "\n\n"
        "both the mean and the final divide COMPUTE, so the result follows the mode's / rule "
        "twice over: rational is exact, fixed-point may round (and a rounded mean compounds "
        "the loss; work at a wider scale via min_fixed_point_precision), float rounds."
    ),
}
